@Library('mylibrary') _
pipeline{
    agent{
       any
    }
    stages{
        stage("A"){
            steps{
                echo "========executing stage A========"
                sayHello
            }

        }
    }
}
