@Library('mylibrary') _
pipeline{
    agent any
    stages{
        stage("A"){
            steps{
                script {
                    echo "========executing stage A========"
                    sayHello()
                }
            }

        }
    }
}
