@Library('my-shared-library@feature1') _

pipeline{
    agent any
    stages{
        stage("A"){
            steps{
                script {
                    echo "========executing stage A========"
                    sayHello('Avijit')
                }
            }

        }
    }
}
