@Library('mylibrary') _

def greet = new org.tesco.GreetingsV2(this)
pipeline{
    agent any
    stages{
        stage("A"){
            steps{
                script {
                    echo "========executing stage A========"
                    greet.greet('Good Evening')
                }
            }

        }
    }
}
