// @Library('my-shared-library@feature1') _

@Library('my-shared-library@feature1')
import org.avijit.GreetingsV2

// here this object passes the steps object to the class
// here env object passes the env object to the class
def greet = new GreetingsV2(this, env)

pipeline{
    agent any
    stages{
        stage("A"){
            steps{
                script {
                    echo "========executing stage A========"
                    greet.greet('Good Evening')
                }
            }

        }
    }
}
