// @Library('my-shared-library@feature1') _

@Library('my-shared-library@feature1')
import org.avijit.GreetingsV2

pipeline{
    agent any
    stages{
        stage("A"){
            steps{
                script {
                    echo "========executing stage A========"
                    def greet = new GreetingsV2(this)
                    greet.greet('Good Evening')
                }
            }

        }
    }
}
