// @Library('my-shared-library@feature1') _

@Library('my-shared-library@feature1')
import static org.avijit.GreetingsV3.greet

pipeline{
    agent any
    stages{
        stage("A"){
            steps{
                script {
                    echo "========executing stage A========"
                    // calling greet static method from script block, here this represents script object 
                    greet(this, 'Good Evening')  
                }
            }

        }
    }
}
